/* Function that appends assets that share like parameters */

function newImage(src, left, bottom) {
    let asset = document.createElement('img');
        asset.src = src;
        asset.style.position = 'fixed';
        asset.style.left = left + 'px';
        asset.style.bottom = bottom + 'px';
        document.body.append(asset);
        return asset;
}

/* Function that build on the previous function and adds an interactive event listener */

function newItem(src, left, bottom) {
    let asset = newImage(src, left, bottom);

    asset.addEventListener("dblclick", function () {
        asset.remove();
    });
    return asset;
}

/* Variables and  functions that create the background images for the enviroment*/

let horizon = window.innerHeight / 1.7;
let heightOfSky = window.innerHeight-horizon;
let heightOfGrass = horizon;

function enviroment(src, left, bottom, width, height){
    for(let h = 0; h < height; h++){
    for(let w = 0; w < width; w++){
    newImage(src, left + w*100, bottom+h*100) 
        };
    };
}

/* List of assets that are generated by the previous series of functions */

enviroment('assets/sky.png', 0, horizon, window.innerWidth/100, heightOfSky/100)
enviroment('assets/grass.png', 0, 0, window.innerWidth/100, heightOfGrass/100)

newImage('assets/green-character.gif', 100, 100)
newImage('assets/pine-tree.png', 450, 200)
newImage('assets/tree.png', 200, 300)
newImage('assets/pillar.png', 350, 100)
newImage('assets/crate.png', 150, 200)
newImage('assets/well.png', 500, 425)

newItem('assets/sword.png', 500, 405)
newItem('assets/sheild.png', 165, 185)
newItem('assets/staff.png', 600, 100)